const USER_KEY = 'tgc_trade_user_id';
const uid = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2) + Date.now().toString(36);
const userId = localStorage.getItem(USER_KEY) || uid();
localStorage.setItem(USER_KEY, userId);

let state = { listings: [], wants: [], offers: [], profile: { id: userId, name: '', location: '', contact: '' } };
let ready = false;
let sharedItem = null;

const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money = n => Number(n) ? `₱${Number(n).toLocaleString()}` : 'Trade';
const initials = n => (n || '?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const norm = s => String(s || '').toLowerCase();
const terms = s => norm(s).split(/[,;\n]+/).map(t=>t.trim()).filter(t=>t.length > 1);
const hasTerm = (text,list) => { const t=norm(text); return list.some(w=>t.includes(w)); };
const tagCls = m => m === 'Trade' ? 'trade' : m === 'Sale' ? 'sale' : '';
const cover = x => (x.photos && x.photos[0]) || x.photo || '';
const isMine = x => x.sellerId === state.profile.id;
const $ = id => document.getElementById(id);
function toast(msg){const t=$('toast'); if(!t)return; t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)}
function contactHref(c){c=(c||'').trim();if(!c)return'';if(/^https?:\/\//i.test(c))return c;if(/^[\d+][\d\s-]{6,}$/.test(c))return 'sms:'+c.replace(/\s/g,'');if(/^@?[\w.]{3,}$/.test(c))return 'https://m.me/'+c.replace('@','');return''}

async function api(path, options={}){
  const r = await fetch(path, { headers:{'Content-Type':'application/json', ...(options.headers||{})}, ...options });
  const data = await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(data.error || `Server error ${r.status}`);
  return data;
}
async function refreshFromServer(silent=false){
  try{
    const data=await api(`/api/state/${encodeURIComponent(state.profile.id)}`);
    state={...state,...data,profile:{...state.profile,...data.profile,id:state.profile.id}};
    ready=true;
    if(!silent) render();
  }catch(e){ready=false; toast('Could not reach TGC TRADE server.'); console.error(e)}
}
let saveTimer;
async function save(){
  clearTimeout(saveTimer);
  saveTimer=setTimeout(async()=>{
    try{
      await api('/api/sync',{method:'POST',body:JSON.stringify({userId:state.profile.id,profile:state.profile,wants:state.wants,listings:state.listings.filter(isMine),offers:state.offers.filter(o=>o.buyerId===state.profile.id||o.sellerId===state.profile.id)})});
    }catch(e){toast('Saved locally on screen, but the server did not accept the change.');console.error(e)}
  },0);
}

function closeModal(){document.querySelectorAll('.modal').forEach(m=>m.remove())}
function modal(html){closeModal();const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-box">${html}</div>`;m.addEventListener('pointerdown',e=>{if(e.target===m)closeModal()});document.body.appendChild(m);const f=m.querySelector('input,textarea,select');if(f)f.focus()}
function profileModal(first=false){modal(`<form onsubmit="saveProfile(event)" class="form-grid"><h2 style="margin:0">${first?'Welcome, collector 👋':'Edit profile'}</h2><div class="muted">${first?'Create your collector identity. It will be used across the shared marketplace.':'Update what other collectors see.'}</div><div><label class="label">Collector name</label><input id="pf_name" class="field" required value="${esc(state.profile.name)}" placeholder="e.g. Marcus"></div><div><label class="label">City / area</label><input id="pf_loc" class="field" value="${esc(state.profile.location)}" placeholder="e.g. Taguig"></div><div><label class="label">Contact</label><input id="pf_contact" class="field" value="${esc(state.profile.contact)}" placeholder="Messenger link, @username or mobile"></div><div style="display:flex;gap:8px"><button class="btn primary" type="submit">Save Profile</button>${first?'':`<button class="btn" type="button" onclick="closeModal()">Cancel</button>`}</div></form>`)}
async function saveProfile(e){e.preventDefault();state.profile.name=$('pf_name').value.trim();state.profile.location=$('pf_loc').value.trim();state.profile.contact=$('pf_contact').value.trim();state.listings.forEach(x=>{if(isMine(x)){x.seller=state.profile.name;x.avatar=initials(state.profile.name);x.location=state.profile.location||x.location;x.contact=state.profile.contact}});closeModal();await save();toast('Profile saved');render()}
function needProfile(){if(state.profile.name)return true;profileModal(true);return false}

function nav(a){const L=(k,h,t)=>`<a class="${a===k?'active':''}" href="#/${h}">${t}</a>`;return `<header class="topbar"><div class="topbar-inner"><a class="logo" href="#/"><span>TGC</span> TRADE</a><nav class="nav">${L('home','','Home')}${L('market','market','Marketplace')}${L('create','create','+ List')}${L('matches','matches','Find My Trade')}${L('wants','wants','My Wants')}${L('offers','offers','Offers')}${L('profile','profile','Profile')}</nav><div class="header-actions"><a class="btn primary small" href="#/create">List a Card</a><div class="hud-wrap">${window.Game?Game.hud():''}</div><a class="avatar" href="#/profile">${initials(state.profile.name)}</a></div></div></header>`}
function layout(c,a='home'){document.getElementById('app').innerHTML=`<div class="shell">${nav(a)}<main>${c}</main><footer class="footer">TGC TRADE · Buy · Sell · Trade · Match<br><span>Independent community platform. Not affiliated with Pokémon or Nintendo.</span></footer></div>`}
const img=(x,emoji='🃏')=>cover(x)?`<img src="${esc(cover(x))}" alt="${esc(x.name)}">`:`<div class="placeholder">${emoji}</div>`;
function listingCard(x){const mine=isMine(x);return `<article class="card"><div class="card-img" onclick="viewListing('${x.id}')" style="cursor:pointer">${img(x)}${x.sold?'<span class="sold-badge">SOLD</span>':''}</div><div class="card-body"><span class="tag ${tagCls(x.mode)}">${esc(x.mode)}</span>${mine?' <span class="tag">YOURS</span>':''}<h3>${esc(x.name)}</h3><div class="muted">${esc(x.set)} · ${esc(x.condition)}</div><div class="card-foot"><span>${esc(x.location||'Philippines')}</span><span class="price">${money(x.price)}</span></div><div class="card-actions"><button class="btn small" onclick="viewListing('${x.id}')">${mine?'Manage':'View'}</button>${mine?'':`<button class="btn success small" onclick="offer('${x.id}')">${x.mode==='Sale'?'Message':'Make Offer'}</button>`}</div></div></article>`}
const emptyCta=(t,b,h)=>`<div class="empty" style="grid-column:1/-1">${t}<br><br><a class="btn primary" href="#/${h}">${b}</a></div>`;

function findMatches(){const mine=state.listings.filter(x=>isMine(x)&&!x.sold),others=state.listings.filter(x=>!isMine(x)&&!x.sold),mw=state.wants.map(norm),out=[];others.forEach(o=>{const ot=terms(o.wants),oText=o.name+' '+o.set;let mutual=null;mine.forEach(m=>{if(!mutual&&hasTerm(m.name+' '+m.set,ot)&&hasTerm(oText,[...mw,...terms(m.wants)]))mutual=m});if(mutual)out.push({kind:'mutual',me:mutual,other:o});else if(hasTerm(oText,mw))out.push({kind:'want',other:o});else{const m=mine.find(m=>hasTerm(m.name+' '+m.set,ot));if(m)out.push({kind:'interest',me:m,other:o})}});return out.sort((a,b)=>['mutual','want','interest'].indexOf(a.kind)-['mutual','want','interest'].indexOf(b.kind))}

function home(){const live=state.listings.filter(x=>!x.sold),latest=live.slice(0,4);layout(`<section class="hero"><div class="hero-card"><div class="tag">THE COLLECTOR MARKETPLACE</div><h1>SHOW WHAT YOU <span class="gradient">HAVE.</span><br>FIND WHAT YOU <span class="gradient">WANT.</span></h1><p>TGC TRADE is a real shared collector marketplace—not a browser-only demo. Post cards, discover other collectors, make offers and build your wants list.</p><div class="hero-buttons"><a class="btn primary" href="#/create">📸 Create a Listing</a><a class="btn" href="#/matches">🤝 Find My Trade</a></div></div><div class="hero-card"><div class="section-head"><h2>Live community</h2></div><div class="stats"><div class="stat"><b>${live.length}</b><span>Live listings</span></div><div class="stat"><b>${state.wants.length}</b><span>Your wants</span></div><div class="stat"><b>${findMatches().length}</b><span>Trade matches</span></div><div class="stat"><b>${state.offers.filter(o=>o.buyerId===state.profile.id).length}</b><span>Your offers</span></div></div><div style="margin-top:16px" class="muted">Every listing you create is sent to the shared TGC TRADE server so another collector can actually see it.</div></div></section><section class="section-head"><div><h2>🔥 Fresh listings</h2><div class="muted">What collectors are posting right now</div></div><a class="btn small" href="#/market">See all</a></section><div class="grid">${latest.map(listingCard).join('')||emptyCta('No listings yet. Be the first collector to post.','📸 Create a Listing','create')}</div>`)}
function market(){layout(`<section class="section-head"><div><h2>Marketplace</h2><div class="muted">Real listings shared by collectors.</div></div><a class="btn primary" href="#/create">+ List a Card</a></section><div class="controls"><input id="q" class="search" placeholder="Search Charizard, Umbreon, 151..." oninput="filterMarket()"><select id="mkMode" class="field" onchange="filterMarket()"><option>All</option><option>Sale</option><option>Trade</option><option>Both</option></select><select id="cond" class="field" onchange="filterMarket()"><option>Any condition</option><option>Near Mint</option><option>Lightly Played</option><option>Moderately Played</option><option>Heavily Played</option><option>Sealed</option></select><select id="sort" class="field" onchange="filterMarket()"><option value="new">Newest</option><option value="lo">Price: low to high</option><option value="hi">Price: high to low</option></select></div><div id="marketGrid" class="grid"></div>`);filterMarket()}
function filterMarket(){const q=norm($('q').value),m=$('mkMode').value,c=$('cond').value,s=$('sort').value;let arr=state.listings.filter(x=>!x.sold&&(!q||norm([x.name,x.set,x.location,x.seller,x.wants].join(' ')).includes(q))&&(m==='All'||x.mode===m)&&(c==='Any condition'||x.condition===c));arr=s==='lo'?arr.sort((a,b)=>a.price-b.price):s==='hi'?arr.sort((a,b)=>b.price-a.price):arr.slice().sort((a,b)=>b.created-a.created);$('marketGrid').innerHTML=arr.length?arr.map(listingCard).join(''):emptyCta('No listings match your search.','Browse again','market')}

function create(){if(!state.profile.name){profileModal(true);return}window.__photos=[];layout(`<section class="section-head"><div><h2>Create your TGC TRADE listing</h2><div class="muted">Your listing will be published to the shared marketplace.</div></div></section><div class="two"><form class="panel form-grid" onsubmit="createListing(event)"><div><label class="label">Card photos (up to 5)</label><div class="drop"><input id="photo" type="file" accept="image/*" multiple><div class="muted" style="margin-top:8px">Photos are resized before upload.</div></div></div><div><label class="label">Card / collection name</label><input id="name" class="field" required placeholder="e.g. Charizard ex"></div><div><label class="label">Set</label><input id="set" class="field" placeholder="e.g. 151, Evolving Skies"></div><div class="two"><div><label class="label">Price (PHP)</label><input id="price" class="field" type="number" min="0" placeholder="4500"></div><div><label class="label">Condition</label><select id="condition" class="field"><option>Near Mint</option><option>Lightly Played</option><option>Moderately Played</option><option>Heavily Played</option><option>Sealed</option></select></div></div><div><label class="label">Listing type</label><select id="mode" class="field"><option>Both</option><option>Sale</option><option>Trade</option></select></div><div><label class="label">What are you looking for?</label><input id="wants" class="field" placeholder="Umbreon, Charizard, vintage..."></div><div><label class="label">Description</label><textarea id="desc" class="field textarea" placeholder="Tell collectors what makes this listing worth a look."></textarea></div><button class="btn primary" type="submit">✨ Publish Listing</button></form><div class="panel preview"><div id="preview" class="share-card"><div class="share-brand">TGC TRADE · COMMUNITY LISTING</div><div class="share-title" id="pname">YOUR CARD</div><div class="share-photo" id="pphoto"><span class="placeholder">🃏</span></div><div class="share-meta"><div><div class="muted">PRICE</div><div class="share-price" id="pprice">₱—</div></div><div style="text-align:right"><div class="muted">CONDITION</div><b id="pcond">Near Mint</b></div></div><div class="share-bottom">TGC TRADE · SHOW WHAT YOU HAVE. FIND WHAT YOU WANT.</div></div></div></div>`);['name','price','condition'].forEach(id=>$(id).addEventListener('input',updatePreview));$('photo').addEventListener('change',async e=>{const fs=[...e.target.files].slice(0,5);const ph=(await Promise.all(fs.map(shrink))).filter(Boolean);window.__photos=ph;if(ph[0])$('pphoto').innerHTML=`<img src="${ph[0]}" alt="preview">`;if(window.Game){Game.onPhoto(ph.length);Game.refreshMeter()}})}
function shrink(file){return new Promise(res=>{const r=new FileReader();r.onload=()=>{const i=new Image();i.onload=()=>{const s=Math.min(1,1000/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=Math.round(i.width*s);c.height=Math.round(i.height*s);c.getContext('2d').drawImage(i,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.78))};i.onerror=()=>res('');i.src=r.result};r.onerror=()=>res('');r.readAsDataURL(file)})}
function updatePreview(){$('pname').textContent=$('name').value||'YOUR CARD';$('pprice').textContent=money($('price').value);$('pcond').textContent=$('condition').value}
async function createListing(e){e.preventDefault();if(!needProfile())return;const p=state.profile;const x={id:uid(),created:Date.now(),name:$('name').value.trim(),set:$('set').value.trim()||'TCG',price:Number($('price').value)||0,mode:$('mode').value,condition:$('condition').value,location:p.location||'Philippines',seller:p.name,sellerId:p.id,avatar:initials(p.name),contact:p.contact,photos:window.__photos||[],description:$('desc').value.trim(),wants:$('wants').value.trim(),sold:false};state.listings.unshift(x);await save();window.__photos=[];if(window.Game)Game.onListingCreated(x,()=>{location.hash=`#/listing/${x.id}`});toast('Listing published to the community');location.hash=`#/listing/${x.id}`}

function viewListing(id){location.hash=`#/listing/${id}`}
function listing(id,shared){const x=shared||state.listings.find(a=>a.id==id);if(!x){toast('Listing not found.');return home()}const mine=!shared&&isMine(x),ph=x.photos&&x.photos.length?x.photos:(x.photo?[x.photo]:[]),href=contactHref(x.contact);layout(`<section class="two"><div class="panel"><div class="card-img big" style="height:480px;border-radius:15px">${ph.length?`<img id="mainPhoto" src="${esc(ph[0])}" alt="${esc(x.name)}">`:'<div class="placeholder">🃏</div>'}${x.sold?'<span class="sold-badge">SOLD</span>':''}</div>${ph.length>1?`<div class="thumbs">${ph.map(p=>`<img src="${esc(p)}" onclick="document.getElementById('mainPhoto').src=this.src" alt="">`).join('')}</div>`:''}</div><div class="panel"><span class="tag ${tagCls(x.mode)}">${esc(x.mode)}</span><h1 style="font-size:42px;line-height:1;margin:13px 0">${esc(x.name)}</h1><div class="muted">${esc(x.set)} · ${esc(x.condition)} · ${esc(x.location||'Philippines')}</div><div class="price" style="font-size:34px;margin:22px 0">${money(x.price)}</div><p style="line-height:1.7;color:#c4ccd8">${esc(x.description||'No description yet.')}</p><div class="panel" style="padding:14px;margin:18px 0;background:#0d1219"><b>I WANT</b><div class="muted" style="margin-top:5px">${esc(x.wants||'Open to offers')}</div></div><div style="display:flex;gap:9px;flex-wrap:wrap">${shared?`<button class="btn success" onclick="saveShared()">➕ Save to my marketplace</button>`:mine?`<button class="btn" onclick="toggleSold('${x.id}')">${x.sold?'↩ Mark available':'✅ Mark as sold/traded'}</button><button class="btn" onclick="delListing('${x.id}')" style="color:var(--danger)">🗑 Delete</button>`:`<button class="btn success" onclick="offer('${x.id}')">💬 ${x.mode==='Sale'?'Message Seller':'Make Trade Offer'}</button>`}${shared?'':`<button class="btn" onclick="shareListing('${x.id}')">📤 Share</button>`}</div><div style="margin-top:22px" class="muted">Seller · <b style="color:var(--text)">${esc(x.seller)}</b>${href&&!mine?` · <a href="${esc(href)}" target="_blank" rel="noopener" style="color:var(--accent2)">Contact</a>`:''}</div></div></section>`,'market')}
async function toggleSold(id){const x=state.listings.find(a=>a.id==id);if(!x)return;x.sold=!x.sold;await save();toast(x.sold?'Marked as sold — removed from marketplace.':'Back on marketplace.');listing(id)}
async function delListing(id){if(!confirm('Delete this listing?'))return;state.listings=state.listings.filter(a=>a.id!=id);await save();toast('Listing deleted');location.hash='#/profile'}

async function shareListing(id){const x=state.listings.find(a=>a.id==id);if(!x)return;const url=location.origin+location.pathname+`#/listing/${x.id}`,text=`${x.name} — ${money(x.price)} · ${x.mode}\n${x.description||''}`;if(navigator.share){try{await navigator.share({title:`${x.name} · TGC TRADE`,text,url});if(window.Game)Game.onShare();return}catch(e){if(e.name==='AbortError')return}}try{await navigator.clipboard.writeText(`${text}\n${url}`);toast('Listing link copied — send it to another collector.')}catch(e){prompt('Copy this link:',url)}if(window.Game)Game.onShare()}
function fbShare(id){shareListing(id)}
function saveShared(){if(!sharedItem)return;if(isMine(sharedItem))return toast("That's your own listing.");const dup=state.listings.find(a=>a.sellerId===sharedItem.sellerId&&a.created===sharedItem.created&&a.name===sharedItem.name);if(dup)return location.hash=`#/listing/${dup.id}`;const n={...sharedItem,id:uid(),sellerId:sharedItem.sellerId};state.listings.push(n);save();toast('Saved to your marketplace');location.hash=`#/listing/${n.id}`}

function offer(id){const x=state.listings.find(a=>a.id==id);if(!x||isMine(x))return toast("That's your own listing.");if(!needProfile())return;const mine=state.listings.filter(a=>isMine(a)&&!a.sold),canTrade=x.mode!=='Sale';modal(`<form onsubmit="sendOffer(event,'${x.id}')" class="form-grid"><h2 style="margin:0">${x.mode==='Sale'?'Message':'Offer to'} ${esc(x.seller)}</h2><div class="muted">${esc(x.name)} · ${money(x.price)}</div>${canTrade&&mine.length?`<div><label class="label">Offer one of your cards</label><select id="of_card" class="field"><option value="">— cash / message only —</option>${mine.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></div>`:''}<div><label class="label">Cash (PHP)</label><input id="of_cash" class="field" type="number" min="0" placeholder="${x.price||''}"></div><div><label class="label">Message</label><textarea id="of_msg" class="field textarea" placeholder="Hi! Is this still available?"></textarea></div><div style="display:flex;gap:8px"><button class="btn success" type="submit">Send Offer</button><button class="btn" type="button" onclick="closeModal()">Cancel</button></div></form>`)}
async function sendOffer(e,id){e.preventDefault();const x=state.listings.find(a=>a.id==id);if(!x)return;const card=$('of_card'),c=card&&state.listings.find(a=>a.id===card.value),cash=Number($('of_cash').value)||0;const parts=[`Hi ${x.seller}, I'm ${state.profile.name} on TGC TRADE. I'm interested in your ${x.name}.`];if(c)parts.push(`I can offer my ${c.name}${cash?` + ${money(cash)}`:''}.`);else if(cash)parts.push(`I can offer ${money(cash)}.`);if($('of_msg').value.trim())parts.push($('of_msg').value.trim());const text=parts.join(' ');state.offers.push({id:uid(),listingId:x.id,listing:x.name,seller:x.seller,sellerId:x.sellerId,buyerId:state.profile.id,contact:x.contact,text,status:'Sent',date:Date.now()});await save();closeModal();if(window.Game)Game.onOffer();navigator.clipboard?.writeText(text).catch(()=>{});const h=contactHref(x.contact);if(h)window.open(h,'_blank','noopener');toast('Offer sent. The seller can now see it in Offers.')}
function offers(){const list=state.offers.slice().sort((a,b)=>b.date-a.date);layout(`<section class="section-head"><div><h2>💬 Offers</h2><div class="muted">Offers you sent and offers collectors sent to you.</div></div></section><div class="matches">${list.map(o=>`<div class="match" style="grid-template-columns:1fr auto"><div class="person"><b>${esc(o.listing)} <span class="muted">· ${esc(o.buyerId===state.profile.id?'To '+o.seller:'From '+o.seller)}</span></b><div class="muted" style="margin:6px 0">${esc(o.text)}</div><small class="muted">${new Date(o.date).toLocaleString()}</small></div><div style="display:grid;gap:7px"><select class="field" onchange="setOffer('${o.id}',this.value)">${['Sent','Accepted','Declined','Completed'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select><button class="btn small" onclick="copyOffer('${o.id}')">Copy</button></div></div>`).join('')||`<div class="empty">No offers yet. Open a listing and make the first move.</div>`}</div>`,'offers')}
async function setOffer(id,s){const o=state.offers.find(a=>a.id==id);if(o){o.status=s;await save();offers();if(s==='Completed'&&window.Game)Game.addXP(15,'deal done')}}
function copyOffer(id){const o=state.offers.find(a=>a.id==id);if(!o)return;navigator.clipboard?.writeText(o.text).then(()=>toast('Copied'),()=>prompt('Copy:',o.text))}

function wants(){const mw=state.wants.map(norm),hits=state.listings.filter(x=>!isMine(x)&&!x.sold&&hasTerm(x.name+' '+x.set,mw));layout(`<section class="section-head"><div><h2>❤️ My Wants</h2><div class="muted">Your hunting list is now used against the shared marketplace.</div></div><button class="btn primary" onclick="addWant()">+ Add a Want</button></section><div class="panel"><div style="display:flex;gap:8px;flex-wrap:wrap">${state.wants.map((w,i)=>`<span class="tag" style="font-size:14px;padding:9px 12px">${esc(w)} <button style="border:0;background:transparent;color:#9ca6b5" onclick="removeWant(${i})">×</button></span>`).join('')||`<div class="empty" style="width:100%">Add cards you're hunting for.</div>`}</div></div><section class="section-head"><div><h2>Potential matches</h2><div class="muted">Listings that line up with your wants.</div></div></section><div class="grid">${hits.map(listingCard).join('')||`<div class="empty" style="grid-column:1/-1">No direct matches yet.</div>`}</div>`,'wants')}
function addWant(){modal(`<form onsubmit="saveWant(event)" class="form-grid"><h2 style="margin:0">Add a want</h2><div class="muted">Separate several cards with commas.</div><input id="w_in" class="field" required placeholder="Umbreon VMAX, Eevee"><div><button class="btn primary" type="submit">Add</button> <button class="btn" type="button" onclick="closeModal()">Cancel</button></div></form>`)}
async function saveWant(e){e.preventDefault();const add=$('w_in').value.split(',').map(s=>s.trim()).filter(s=>s&&!state.wants.some(w=>norm(w)===norm(s)));if(!add.length){closeModal();return toast('Already on your list.')}state.wants.push(...add);await save();closeModal();wants();if(window.Game)Game.onWant()}
async function removeWant(i){state.wants.splice(i,1);await save();wants()}
function matches(){const m=findMatches(),lab={mutual:'🤝 Perfect trade',want:'🎯 You want this',interest:'👀 They want your card'};layout(`<section class="hero-card" style="margin-bottom:22px"><div class="tag">SMART MATCHING</div><h1 style="font-size:45px">Find the collector who has <span class="gradient">what you want.</span></h1><p>Matching runs across the shared marketplace using your listings, your “I want” fields and your My Wants list.</p></section><section class="section-head"><div><h2>🤝 Potential matches</h2><div class="muted">${m.length} found</div></div></section><div class="matches">${m.map(r=>`<div class="match"><div class="person">${r.me?`<b>You have</b><div>${esc(r.me.name)}</div><small class="muted">${esc(r.me.set)}</small>`:`<b>You want</b><div>${esc(state.wants.find(w=>hasTerm(r.other.name+' '+r.other.set,[norm(w)]))||'')}</div>`}</div><div class="arrow">↔</div><div class="person"><b>${esc(r.other.seller)} has</b><div>${esc(r.other.name)}</div><small class="muted">${lab[r.kind]} · ${money(r.other.price)}</small><div style="display:flex;gap:6px;margin-top:8px"><button class="btn small" onclick="viewListing('${r.other.id}')">View</button><button class="btn success small" onclick="offer('${r.other.id}')">Offer</button></div></div></div>`).join('')||`<div class="empty">No matches yet. Add wants or list cards with what you're looking for.</div>`}</div>`,'matches')}
function profile(){const mine=state.listings.filter(isMine),p=state.profile;layout(`<section class="panel"><div class="profile-head"><div class="big-avatar">${initials(p.name)}</div><div><h1 style="margin:0">${esc(p.name||'New collector')}</h1><div class="muted">📍 ${esc(p.location||'Add your city')} · Collector${p.contact?` · ${esc(p.contact)}`:''}</div></div><button class="btn" style="margin-left:auto" onclick="profileModal()">Edit profile</button></div></section>${window.Game?Game.profilePanel():''}<section class="section-head"><div><h2>My Listings</h2><div class="muted">${mine.length} posted · ${mine.filter(x=>x.sold).length} sold/traded</div></div><a class="btn primary" href="#/create">+ Add Card</a></section><div class="grid">${mine.slice().reverse().map(listingCard).join('')||emptyCta("You haven't listed anything yet.",'📸 Create a Listing','create')}</div><section class="section-head"><h2>Account</h2></section><div class="panel"><div class="muted" style="margin-bottom:12px">Your account identity is stored locally so this device can reconnect to your server profile. Marketplace data is shared through the TGC TRADE server.</div><button class="btn" onclick="refreshFromServer()">↻ Refresh community data</button></div>`,'profile')}

function render(){closeModal();const p=location.hash.slice(2)||'/';window.scrollTo(0,0);if(p==='/')home();else if(p==='/market')market();else if(p==='/create')create();else if(p==='/wants')wants();else if(p==='/matches')matches();else if(p==='/offers')offers();else if(p==='/profile')profile();else if(p.startsWith('/listing/'))listing(p.split('/')[2]);else home();if(ready&&!state.profile.name&&p==='/'&&!render.asked){render.asked=1;profileModal(true)}}
window.addEventListener('hashchange',render);
window.addEventListener('load',async()=>{await refreshFromServer(true);render();setInterval(()=>refreshFromServer(true),10000)});
